language: node_js
node_js:
  - 'stable'
  - 'lts/*'
  - '10'
script:
  - npm test
  - cat example.txt | ./parse.js | ./visualize.js >/dev/null
cache: npm
notifications:
  email:
    on_success: never
